"""add brand volume percentage columns

Revision ID: 9d251f5be710
Revises: 101034c2460a
Create Date: 2025-09-26 18:11:19.382112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d251f5be710'
down_revision: Union[str, None] = '101034c2460a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('product', sa.Column('volume', sa.String(), nullable=True))
    op.add_column('product', sa.Column('percentage', sa.String(), nullable=True))
    op.create_index(op.f('ix_product_brand'), 'product', ['brand'], unique=False)
    op.create_index(op.f('ix_product_percentage'), 'product', ['percentage'], unique=False)
    op.create_index(op.f('ix_product_volume'), 'product', ['volume'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_volume'), table_name='product')
    op.drop_index(op.f('ix_product_percentage'), table_name='product')
    op.drop_index(op.f('ix_product_brand'), table_name='product')
    op.drop_column('product', 'percentage')
    op.drop_column('product', 'volume')
    op.drop_column('product', 'brand')
    # ### end Alembic commands ###
